### ISSUE TITLE
SyntaxError: Unexpected token ... on version 1.0.11

### ISSUE THREAD

**Issue by GuidoZuccarelli** [whitlockjc/path-loader#50]
Your patch version update is actually a major version upgrade since you have bumped **superagent** dependency from _3.8.3_ to _7.1.6_.
And superagent has this upgrade on its dependency:

formidable@**1.2.6** -> formidable@**2.0.1**

Which now on my version of node hits the following error:

```
formidable/src/index.js:27
  ...parsers,
  ^^^
SyntaxError: Unexpected token ...
```

**Comment by whitlockjc** [comment]
Fixed in `path-loader@1.0.12`.

**Comment by ssalenik** [comment]
> Fixed in `path-loader@1.0.12`.

Hi, what is the fix in `1.0.12`?
I'm still having the same issue on my project as OP. Unfortunately using a very old node.js, but is there a reason this change can't be a major version bump? Thank you.

**Comment by whitlockjc** [comment]
I just removed the Node.js engine bump from v14+ back to what it was before.  The whole point behind `1.0.1[2]` was to bump Superagent and if doing that resulted in a Node.js engine bump indirectly, the only thing I know to do would be to rollback all changes and make the superagent bump a major version change, or you can just use the explicit `path-loader@1.0.10` for your stuff.  Due to transitive dependencies and their ability to break things, I'm not sure the best way to handle this.

**Comment by ssalenik** [comment]
Yeah, for now I've forced `1.0.10`.
I believe the ideal fix would be as you said to roll back the changes and then make it into a major version change. But I'm also not sure.

**Comment by whitlockjc** [comment]
Yeah, transitive dependencies are a pain.  To me, updating dependencies should be a patch release as the functionality of this library isn't changing and it _shouldn't_ break things.  But clearly it is.  The same with altering the Node.js engine for supporting LTS+, the code isn't changing and using a new engine shouldn't break things, but if modules use language features only available in newer engines, it's breaking.  Such a pain.
